Support passing arguments to plugins
amberframework/amber pull request #1236
Opened 2020-10-20 15:38 UTC by andrewc910

### Description of the Change

Small change that allows plugin users to pass arguments for rendering templates. The syntax is:
```sh
amber plugin mochi granite
```

With `granite` being the single argument. 

### Alternate Designs

I would of prefer the arguments in a hash with keys being number or an array. It seems like liquid doesn't like `args.0` or `args[0]` as it keeps throwing errors on me. 

### Benefits

Plugin templates can be more dynamic. For example, my shard Mochi supports both Granite and Jennifer ORM's. Rather than having shards "mochi-granite-plugin" and "mochi-jennifer-plugin" that would be almost duplicates of each other, I can use simple `if` statements in my plugin templates.

`if args.a == "granite"`

### Possible Drawbacks

It's possible users don't pass in the proper arguments and the template doesn't come out right. However, if we go with my other PR about the config.yml file. We can allow plugin authors to define x number of arguments required for rendering. If a user doesn't pass in exactly X arguments, we throw an error. It's not full proof but nothing is. 

### About the args Hash

I initially tried setting the Liquid context as an array. I figured a `args[0]` syntax would be acceptable. Well I guess I ran into a bug because `args[0]`, `args["0"]` and `args.0` all throw `Invalid Boolean operation  (Exception)` errors. It seems Liquid doesn't like numbers. So i decided to use a hash where it looks like `{"a" => "granite", "b" => "false"}`. Plugin authors can access the variables with `args.a`. If someone knows how to fix this, I am completely open to it. I think `args.1` would be best but I am open to other ideas.

2020-10-21 12:12 UTC, drujensen requested changes
Can you add some test coverage for this feature?

2020-10-21 17:28 UTC, andrewc910 commented
A spec has been added.

I also changed the naming scheme for arguments. Plugin authors define argument names in their config.yml.

```yml
args:
  - name
  - age
```

Then these can be accessed in liquid templates with `args.name` & `args.age`. Let me know what you think.

2020-10-21 22:51 UTC, andrewc910 commented
@drujensen I updated the first comment of this PR to include an explanation of all changes. Please let me know if any additional changes need to be made.

2020-11-10 01:59 UTC, eliasjpr approved these changes

2020-11-11 20:58 UTC, merged