Feature/change default orm to jennifer
amberframework/amber pull request #1289
Opened 2022-07-12 13:48 UTC by crimson-knight

### Description of the Change

This PR changes the default ORM to Jennifer, and integrates the CLI commands for Jennifer into the `amber` CLI tool.

A couple of nice changes:
- Detects the version of node and updates the node-sass dependency versions so that styling properly compiles if you're using Node 14+
- Changed the 3rd link in the auto generated Amber app to link to the discord
- Adds the `Sam` CLI utility to make running tasks easy.

Potential breaking change:
- The I18n shard that Jennifer relies on removes the `force_locale: context.locale` feature. I think this means we no longer have "dynamic" language detection. I don't see any tests currently for this, but it's worth trying to add this back in and I think using URL based language detection. The default language can be configured easily, and all the translation capabilities work it is just not dynamic.

### Benefits

Not having to solo-maintain an ORM and using an ORM that has more of the db-specific data types working (mostly looking at Postgres)

### Possible Drawbacks

Currently, this tightly couples the Amber CLI tool with the Sam CLI tool provided by Jennifer. The Sam tool is pretty handy for rake/make-like jobs, so I'm pretty happy with doing this. I think there will be a lot of situations where other devs will want to run tasks (data migrations/alterations, etc). so this will be a handy improvement.

2022-07-13 01:51 UTC, drujensen commented
Hi Seth.  Thanks for submitting this PR.  This is a very large PR and will be difficult to review.  I will give it a spin when I get a chance.  Will you be able to update the documentation as well?

2022-07-13 02:06 UTC, drujensen requested changes
I tried using `amber g auth user` and I'm getting an error: `class User < Granite::Base`.  You will need to update all of the scaffolding to use Jennifer.

2022-07-13 02:09 UTC, drujensen commented
Also, looks like the `Dockerfile` is still using crystal 1.0.0 and doesn't build.

2022-07-13 09:59 UTC, crimson-knight commented
Thanks @drujensen for the review, you're right I haven't update the auth generator yet. I had forgotten about the docker file, but I will need to update that in a different PR since that's a different scope from this one.

I'll definitely get the documentation updated once this PR is done and I know the full extent of the changes.

2022-07-13 10:34 UTC, crimson-knight commented
Oh yeah, FWIW a lot of the file changes are just tweaks suggested by Ameba so I could get the `bin/amber_spec` to pass.

2022-10-31 16:52 UTC, eliasjpr commented on src/amber/cli/commands/new.cr
> +        #cwd = Dir.current; Dir.cd(full_path_name)
Is this intentional? Maybe you want to uncomment these lines

2022-10-31 16:52 UTC, eliasjpr commented on src/amber/cli/commands/pipelines.cr
> +          result.flat_map { |pipes_and_plugs| pipes_and_plugs[:pipes] }.uniq!.each do |pipe|
👍

2022-10-31 16:52 UTC, eliasjpr commented on src/amber/cli/helpers/process_runner.cr
> +        if !procs.empty?
Maybe: `unless procs.empty?`

2022-10-31 16:59 UTC, crimson-knight commented
Closing this out in favor of a different approach that allows for any ORM to be used and connected to the generators/CLI tool

2022-10-31 16:59 UTC, closed without merging